In [2]:
"""
This cell writes the desired class labels into files (encrypted channel)
"""
# import numpy as np
# import os

# class_idx_dir = "/home/zl310/cs585_project/vmoe/chosen_class_idx_encrypted/"
# rng = np.random.default_rng()
# num_total_classes = 1000
# num_chosen_classes_list = [2, 4, 8, 16, 32, 64]

# class_idx = np.array(range(num_total_classes))
# chosen_64 = rng.permutation(class_idx)[0:64]

# for num_chosen_classes in num_chosen_classes_list:
#     chosen_class_idx = chosen_64[0:num_chosen_classes]
#     np.save(os.path.join(class_idx_dir, f"n_{num_chosen_classes}.npy"), chosen_class_idx)

import numpy as np
import os

class_idx_dir = "/home/zl310/cs585_project/vmoe/chosen_class_idx_encrypted/"
num_chosen_classes_list = [2, 4, 8, 16, 32, 64]

for num_chosen_classes in num_chosen_classes_list:
    test_file = np.load(os.path.join(class_idx_dir, f"n_{num_chosen_classes}.npy"))
    print(test_file)

[472 361]
[472 361 991 143]
[472 361 991 143 390 297 485 540]
[472 361 991 143 390 297 485 540 307 783 148  28 351 645 879 333]
[472 361 991 143 390 297 485 540 307 783 148  28 351 645 879 333 957 724
 444  36 902 564 887 916 947 709 180 917 945  14 207 762]
[472 361 991 143 390 297 485 540 307 783 148  28 351 645 879 333 957 724
 444  36 902 564 887 916 947 709 180 917 945  14 207 762 139 222 750 723
 505 976 741  61 453 410 721 194 580 690 761 336  43 402 237 216 583 303
 349 891  76 458 128 597 846 178 235 909]
